/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Text: THREE.Mesh
    Text_1: THREE.Mesh
    Text_2: THREE.Mesh
    Text_3: THREE.Mesh
    key: THREE.Mesh
    Cube: THREE.Mesh
    Cube_1: THREE.Mesh
    key_01001: THREE.Mesh
  }
  materials: {
    white: THREE.MeshStandardMaterial
    plastic: THREE.MeshPhysicalMaterial
    screen: THREE.MeshPhysicalMaterial
    light: THREE.MeshStandardMaterial
    ['key red.001']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshPhysicalMaterial
    ['key black']: THREE.MeshPhysicalMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/smarttv.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.02, 0.71, 0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.19}>
        <mesh castShadow receiveShadow geometry={nodes.Text.geometry} material={materials.white} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_1.geometry}
          material={materials.plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_2.geometry}
          material={materials.screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_3.geometry}
          material={materials.light}
        />
      </group>
      <group position={[-1, 0.04, 1]} rotation={[-1.35, 0, 0]} scale={[-0.03, -0.02, -0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials['key black']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.key_01001.geometry}
          material={materials.white}
          position={[-4.47, 1.8, 0.99]}
          rotation={[-0.19, 0, 0]}
          scale={[-0.03, -0.02, -0.02]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/smarttv.glb')
